### PR TITLE
Update dependencies and verify that UI still works

### PR DESCRIPTION
**Pull request by johpiip**
To do from #97:
- [x] Update (vulnerable) packages
- [x] UI does not freeze
- [x] Selecting directiories works
- [x] Overall, UI behaves the same as before
- [x] Review security regarding `nodeIntegration`, `contextIsolation`, and `enableRemoteModule`

### CODE REVIEW

**Comment by johpiip** [comment]
https://www.electronjs.org/docs/breaking-changes#behavior-changed-webkitdirectory-attribute-for-input-typefile-now-lists-directory-contents

**Comment by johpiip** [comment]
https://github.com/HSLdevcom/helmet-ui/pull/100/commits/ca26706b9c45546df40a3fe9bf365c55fbf2a316 may fix #19, more tests needed.

**Comment by johpiip** [comment]
Packages with major version bumps:
```
> npm outdated
Package         Current   Wanted  Latest  Location
del               5.1.0    5.1.0   6.0.0  helmet-ui
electron-store    4.0.0    4.0.0   8.0.0  helmet-ui
python-shell      1.0.8    1.0.8   3.0.0  helmet-ui
react           16.14.0  16.14.0  17.0.2  helmet-ui
react-dom       16.14.0  16.14.0  17.0.2  helmet-ui
uuid              3.4.0    3.4.0   8.3.2  helmet-ui
```

**Comment by johpiip** [comment]
Regarding `nodeIntegration`, `contextIsolation`, and `enableRemoteModule`...

As Electron was bumped from v5 to v13, there were two major global settings changed:
- In v10: "Changed the default value of `enableRemoteModule` to `false`."
- In v12: "Deprecated the `remote` module. It is replaced by `[@electron/remote](https://github.com/electron/remote)`."
- In v12: "Changed the default value of `contextIsolation` to `true`."

Right now, Helmet-UI does not work without setting `contextIsolation` explicitly to `false` and `enableRemoteModule` to `true`. This is a security concern an dshould be tackled in near future.

`nodeIntegration` is not a security concern but a way to connect Electron and Nodejs so no changes needed there.

**Review by zptro — APPROVED** [review]

**Pull request merged**
