### PR TITLE
Increase size of full matrices

### PR DESCRIPTION
**Pull request by johpiip**
When "Tallenna ajanjaksojen matriisit Emme-projektin Database-kansioon" (`SAVE_MATRICES_IN_EMME` / `--save-emme-matrices`) is on, the model run actually needs 400 full matrices, not 300.

Otherwise, we get:
```
Traceback (most recent call last):
  File "C:\Users\PiippJo\Downloads\helmet-model-system-4.1.3 (1)\helmet-model-system-4.1.3\Scripts\helmet.py", line 261, in <module>
    main(args)
  File "C:\Users\PiippJo\Downloads\helmet-model-system-4.1.3 (1)\helmet-model-system-4.1.3\Scripts\helmet.py", line 95, in main
    args.use_fixed_transit_cost, iterations==0)
  File "C:\Users\PiippJo\Downloads\helmet-model-system-4.1.3 (1)\helmet-model-system-4.1.3\Scripts\modelsystem.py", line 170, in assign_base_demand
    self.ass_model.prepare_network(self.zdata_forecast.car_dist_cost)
  File "C:\Users\PiippJo\Downloads\helmet-model-system-4.1.3 (1)\helmet-model-system-4.1.3\Scripts\assignment\emme_assignment.py", line 80, in prepare_network
    default_value=0, overwrite=True)
  File "inro\director\logging\trail.py", line 270, in __trace
  File "standard\inro\emme\data\matrix\create_matrix.py", line 451, in __call__
  File "standard\inro\emme\utility\validate.py", line 716, in Integer
  File "standard\inro\emme\utility\validate.py", line 689, in _validate_number
inro.emme.core.exception.ArgumentError: matrix_id number: expected a value between 1 and 300.
```

### CODE REVIEW

**Review by zptro — COMMENTED** [review]
This actually depends on what you set as the first matrix id in the model run. The default in the GUI is 100 and in this case you indeed need 400 matrices. Maybe we should instead set the default to 0?

**Review by eevavesaoja — CHANGES_REQUESTED** [review]
This is ok, but Jens' suggestions is probably preferable for saving space if his suggestion also fixes the issue

**Comment by johpiip** [comment]
Sorry for my very late reply! We can change the UI default too! I need to check one more thing from you, @zptro! Say we do the following:

1. We run a model run "Ve0" and save matrices to 0-299. Ve0 matrices appear on numbers mf1-299.
2. We run a second model run "Ve1" and save matrices to 300-599. Ve1 matrices appear on numbers mf301-599.

Now that we have Ve0 "\_aht" matrices on 1-99, they don't get overwritten by dummy "\_" matrices from the second model run, do they? I tested it and based on matrix names, they don't, but I want to check. 😄

**Comment by zptro** [comment]
> Sorry for my very late reply! We can change the UI default too! I need to check one more thing from you, @zptro! Say we do the following:
> 
> 1. We run a model run "Ve0" and save matrices to 0-299. Ve0 matrices appear on numbers mf1-299.
> 2. We run a second model run "Ve1" and save matrices to 300-599. Ve1 matrices appear on numbers mf301-599.
> 
> Now that we have Ve0 "_aht" matrices on 1-99, they don't get overwritten by dummy "_" matrices from the second model run, do they? I tested it and based on matrix names, they don't, but I want to check. 😄

Sorry, I had missed this one. No, no "dummy" matrices should be there if run both with "save matrices".

**Comment by hsl-petrhaj** [comment]
Isn't the mf0-99 for vrk matrices? What would be the point of overriding them? I think it is better to adjust the instructions for the Emme bank creation.
@zptro  @johpiip

**Comment by zptro** [comment]
> Isn't the mf0-99 for vrk matrices? What would be the point of overriding them? I think it is better to adjust the instructions for the Emme bank creation. @zptro @johpiip

What vrk matrices? We only do assignment for aht, pt and iht. The demand model calculates demand for the whole day, but that is not stored in EMME.

**Review by eevavesaoja — APPROVED** [review]
Tämä ok!

**Comment by hsl-petrhaj** [comment]
> > Isn't the mf0-99 for vrk matrices? What would be the point of overriding them? I think it is better to adjust the instructions for the Emme bank creation. @zptro @johpiip
> 
> What vrk matrices? We only do assignment for aht, pt and iht. The demand model calculates demand for the whole day, but that is not stored in EMME.

What was the reason to go with 100-399 in the first place then?

**Comment by zptro** [comment]
> > > Isn't the mf0-99 for vrk matrices? What would be the point of overriding them? I think it is better to adjust the instructions for the Emme bank creation. @zptro @johpiip
> > 
> > 
> > What vrk matrices? We only do assignment for aht, pt and iht. The demand model calculates demand for the whole day, but that is not stored in EMME.
> 
> What was the reason to go with 100-399 in the first place then?
> 
> Edit: Now the mf0-mf99 does not seem to add much value, but at least there is clear separation between time period matrices and "runtime" matrices. Or am I getting the "runtime" matrices wrong? Are they somehow 0-299 and then they shift to 100-399?

One point of saving them in mf100-mf399 is that if you *afterwards* decides to do another model run where you do *not* "save matrices", you risk overwriting your previously saved matrices, because the second model run automatically uses mf0-mf99 for "runtime" matrices. But 300 matrices is the minimum requirement for doing *one* model run and saving the resulting matrices. The meaning of the plus sign is that if you do several model runs and want to store matrices, you will need more than 300 matrices.

**Comment by hsl-petrhaj** [comment]
Solved here:
https://github.com/HSLdevcom/helmet-docs/pull/20

**Pull request closed without merging**
